
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft", "emendatusenigmatica", "immersiveengineering", "thermal", "create", "mekanism", "kubejs", "industrialforegoing", "botania", "quark"]

