#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["emendatusenigmatica", "minecraft", "immersiveengineering", "thermal", "create", "mekanism", "kubejs", "industrialforegoing", "botania", "quark"]

