#If you login anonymously you can read chat, but you will not be able to type to Twitch chat from within Minecraft.
useAnonymousLogin = false
showWhispers = false
disableUserColors = false
disableNameBadges = false
#Set this if you're on a public computer or concerned about security. You will have to re-authenticate every time you start Minecraft.
doNotStoreToken = false
#Range: > -2147483648
port = 6667
#Messages by these users will not display in chat. Useful to hide bots for example.
userBlacklist = []

