#Microphone activation type
#Allowed Values: PTT, VOICE
microphone_activation_type = "PTT"
#The threshold for voice activation in dB
#Range: -127.0 ~ 0.0
voice_activation_threshold = -50.0
#The voice chat volume
#Range: 0.0 ~ 2.0
voice_chat_volume = 1.0
#The voice chat microphone amplification
#Range: 0.0 ~ 4.0
microphone_amplification = 1.0
#The size of the audio output buffer in packets
#Higher values mean a higher latency, but less crackles
#Increase this value if you have an unstable internet connection
#Range: 1 ~ 16
output_buffer_size = 6
#The microphone used by the voice chat
#Empty for default device
microphone = ""
#The microphone used by the voice chat
#Empty for default device
speaker = ""
#If the microphone is muted (only when using voice activation)
muted = false
#If the voice chat is disabled (sound and microphone off)
disabled = false
#If the voice chat should use semi 3D stereo sound
stereo = true
#If the voice chat icons should be hidden
hide_icons = true
#The time it takes for the microphone to deactivate when using voice activation
#A value of 1 means 20 milliseconds, 2=40 ms, 3=60 ms, ...
#Range: 0 ~ 100
voice_deactivation_delay = 25

